export const FETCHING_PEOPLE = 'FETCHING_PEOPLE'
export const FETCHING_PEOPLE_SUCCESS = 'FETCHING_PEOPLE_SUCCESS'
export const FETCHING_PEOPLE_FAILURE = 'FETCHING_PEOPLE_FAILURE'
export const FETCH_USER = 'FETCH_USER'

export const FETCH_PEOPLE_SHOP_SUCCESS = 'FETCH_PEOPLE_SHOP_SUCCESS'
export const FETCH_PEOPLE_SHOP_FAILURE = 'FETCH_PEOPLE_SHOP_FAILURE'